### ISSUE TITLE
How to wire the mpu to raspberry pi3

### ISSUE THREAD

**Issue by Araas-Boloorchi** [matpalm/ros-mpu6050-node#1]
Hello,
I want to synch my Imu and a camera with an external trigger with the frame rate of 200 Hz
![photo_2018-09-16_15-41-12](https://user-images.githubusercontent.com/43946196/47613521-b9930080-da5e-11e8-98d9-bb46be19fbae.jpg)
 and I connected my IMU like the picture is it as same as what it should be for your code?

**Comment by matpalm** [comment]
Yeah I can't remember off the top of my head where the I2C pins are but that looks about right
