### ISSUE TITLE
would you please add usage ?

### ISSUE THREAD

**Issue by Araas-Boloorchi** [matpalm/ros-mpu6050-node#2]

**Comment by matpalm** [comment]
can you elaborate on your question? there's no real usage beyond what the README says; the node will read the imu and publish a `mpu6050` topic

**Comment by Araas-Boloorchi** [comment]
Sorry I mean: is there any chance to launch it independentle by roslaunch

**Comment by matpalm** [comment]
Yes, that's the idea. you build this node as a package under a catkin workspace. Work through this tute & you'll see, when a package is created just drop this code in instead http://wiki.ros.org/catkin/Tutorials/create_a_workspace
